name: Dependabot auto-squash
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    env:
      REPO_OWNER: riges
      REPO_NAME: bmw-finder
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository_owner == '${{ env.REPO_OWNER }}' && github.event.repository.name == '${{ env.REPO_NAME }}'
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2
      - name: Enable auto-squash for Dependabot PRs (patch only, prod or dev)
        if: |
          steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' ||
          (steps.dependabot-metadata.outputs.update-type == 'grouped' && steps.dependabot-metadata.outputs.dependency-type == 'development') ||
          (steps.dependabot-metadata.outputs.update-type == 'grouped' && steps.dependabot-metadata.outputs.dependency-type == 'production' && steps.dependabot-metadata.outputs.target-branch == 'patch')
        run: gh pr merge --auto --squash ${{github.event.pull_request.number}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
